# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :internal do
    store_password = "password123"
    # prompt(text: "Signing Store Password: ", secure_text: true) # 1BLbah2ovexNpQHqBrEt ENV[PLAY_STORE_PASSWORD]
    key_password =  "password123"
    # prompt(text: "Alias Key Password: ", secure_text: true) # 1BLbah2ovexNpQHqBrEt ENV[KEYSTORE_PASSWORD]
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "alias_name",
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft'
    )
  end

  lane :alpha do
    store_password = "password123"
    # prompt(text: "Signing Store Password: ", secure_text: true) # 1BLbah2ovexNpQHqBrEt ENV[PLAY_STORE_PASSWORD]
    key_password =  "password123"
    # prompt(text: "Alias Key Password: ", secure_text: true) # 1BLbah2ovexNpQHqBrEt ENV[KEYSTORE_PASSWORD]
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "alias_name",
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: 'alpha',
      release_status: 'draft'
    )
  end

  lane :beta do
    store_password = "password123"
    # prompt(text: "Signing Store Password: ", secure_text: true) # 1BLbah2ovexNpQHqBrEt ENV[PLAY_STORE_PASSWORD]
    key_password =  "password123"
    # prompt(text: "Alias Key Password: ", secure_text: true) # 1BLbah2ovexNpQHqBrEt ENV[KEYSTORE_PASSWORD]
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "alias_name",
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: 'beta',
      release_status: 'draft'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
